[project]
name = "bottle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.0",
    "jinja2>=3.1.6",
    "python-multipart>=0.0.22",
    "sqlmodel>=0.0.32",
    "tzdata>=2025.3",
    "uvicorn>=0.40.0",
]
